---

- name: Install Cinder Packages
  yum: 
    name: '{{ item }}'
    state: latest
  with_items:
    - 'openstack-cinder'
    - 'openstack-utils'
    - 'openstack-selinux'
    - 'device-mapper-multipath'

- name: Configure Cinder Debug
  ini_file:
    dest: /etc/cinder/cinder.conf
    section: DEFAULT
    option: debug
    value: "{{ common.debug }}"
  notify:
   - Restart Cinder
   - Restart Cinder Scheduler

- name: Configure Cinder SQL Connection
  ini_file: 
    dest: /etc/cinder/cinder.conf
    section: database
    option: connection
    value: "mysql://{{ cinder.dbuser}}:{{cinder.dbpassword}}@{{ common.mysql_host}}/{{ cinder.dbname }}"
  notify:
   - Restart Cinder
   - Restart Cinder Scheduler

- name: Configure Cinder Rabbit Backend
  ini_file: 
    dest: /etc/cinder/cinder.conf
    section: DEFAULT
    option:  rpc_backend
    value: cinder.openstack.common.rpc.impl_kombu
  notify:
   - Restart Cinder
   - Restart Cinder Scheduler

- name: Configure Cinder Rabbit Hosts
  ini_file: 
    dest: /etc/cinder/cinder.conf
    section: oslo_messaging_rabbit
    option: rabbit_hosts
    value: "{{ common.rabbit_hosts | append(':5672') | join(',')}}"
  notify:
   - Restart Cinder
   - Restart Cinder Scheduler

- name: Configure Cinder Rabbit User
  ini_file: 
    dest: /etc/cinder/cinder.conf
    section: oslo_messaging_rabbit
    option: rabbit_userid
    value: "{{ common.rabbit_user }}"
  notify:
   - Restart Cinder
   - Restart Cinder Scheduler

- name: Configure Cinder Rabbit Password
  ini_file: 
    dest: /etc/cinder/cinder.conf
    section: oslo_messaging_rabbit
    option: rabbit_password
    value: "{{ common.rabbit_password }}"
  notify:
   - Restart Cinder
   - Restart Cinder Scheduler

- name: Configure Cinder Rabbit Virtual Host
  ini_file: 
    dest: /etc/cinder/cinder.conf
    section: oslo_messaging_rabbit
    option: rabbit_virtual_host
    value: /
  notify:
   - Restart Cinder
   - Restart Cinder Scheduler

- name: Configure Cinder Keystone Strategy
  ini_file: 
    dest: "/etc/cinder/cinder.conf"
    section: DEFAULT
    option: auth_strategy
    value: keystone
  notify:
   - Restart Cinder
   - Restart Cinder Scheduler

- name: Configure Cinder Keystone Uri
  ini_file: 
    dest: "/etc/cinder/cinder.conf"
    section: keystone_authtoken
    option: identity_uri
    value: "{{ keystone_identity_uri }}"
  notify:
   - Restart Cinder
   - Restart Cinder Scheduler

- name: Configure Cinder Keystone Tenant
  ini_file: 
    dest: "/etc/cinder/cinder.conf"
    section: keystone_authtoken
    option: admin_tenant_name
    value: services
  notify:
   - Restart Cinder
   - Restart Cinder Scheduler

- name: Configure Cinder Keystone User
  ini_file: 
    dest: "/etc/cinder/cinder.conf"
    section: keystone_authtoken
    option: admin_user
    value: cinder
  notify:
   - Restart Cinder
   - Restart Cinder Scheduler

- name: Configure Cinder Keystone Password
  ini_file: 
    dest: "/etc/cinder/cinder.conf"
    section: keystone_authtoken
    option: admin_password
    value: "{{ cinder.password }}" 
  notify:
   - Restart Cinder
   - Restart Cinder Scheduler

- name: Check Cinder Database Version
  shell: cinder-manage db version
  register: cinder_db_version
  changed_when: false

- name: Populate Cinder Database
  run_once: yes
  shell: cinder-manage db sync
  when: cinder_db_version.stdout == "0"

- name: Create Cinder User
  keystone_user:
    state: present
    endpoint: "{{ keystone_admin_url }}"
    token: "{{ keystone.admin_token }}"
    user: cinder
    tenant: services
    password: "{{ cinder.password }}"

- name: Grant Cinder Admin Role
  keystone_user:
    endpoint: "{{ keystone_admin_url }}"
    token: "{{ keystone.admin_token }}"
    tenant: services
    user: cinder
    role: admin

- name: Create Cinder Service And Endpoint
  keystone_service: 
    name: cinder
    type: volume
    description: "Cinder Volume Service"
    publicurl: "{{ cinder_public_url }}"
    internalurl: "{{ cinder_internal_url }}"
    adminurl: "{{ cinder_admin_url }}"
    endpoint: "{{ keystone_internal_url }}"
    login_user: admin
    login_password: "{{ keystone.admin_password }}"
    tenant_name: admin
    region: "{{ common.region }}"

- name: Create Cinder V2 Service And Endpoint
  keystone_service: 
    name: cinderv2
    type: volumev2
    description: "Cinder Volume Service"
    publicurl: "{{ cinderv2_public_url }}"
    internalurl: "{{ cinderv2_internal_url }}"
    adminurl: "{{ cinderv2_admin_url }}"
    endpoint: "{{ keystone_internal_url }}"
    login_user: admin
    login_password: "{{ keystone.admin_password }}"
    tenant_name: admin
    region: "{{ common.region }}"

- name: Enable Cinder Service
  service:
    name: "openstack-cinder-{{ item }}"
    enabled: yes
    state: started
  with_items:
   - api
   - scheduler
