---

- name: Set Glance Variables
  set_fact:
    public_url: "{{ glance.public_url | default('http://' ~ common.controller_host ~ ':9292') }}"
    internal_url: "{{ glance.internal_url | default('http://' ~ common.controller_host ~ ':9292') }}"
    admin_url: "{{ glance.admin_url | default('http://' ~ common.controller_host ~ ':9292') }}"
    keystone_url: "{{ keystone.internal_url | default('http://' ~ common.controller_host ~ ':5000/v2.0') }}"

- name: Install Glance
  yum: 
    name: '{{ item }}'
    state: latest
  with_items:
    - 'openstack-glance'
    - 'openstack-utils'
    - 'openstack-selinux'

- name: Configure Glance SQL Connection
  ini_file: 
    dest: "/etc/glance/glance-{{ item }}.conf"
    section: DEFAULT
    option: sql_connection
    value: "mysql://{{ glance.dbuser}}:{{glance.dbpassword}}@{{ common.controller_host}}/{{ glance.dbname }}"
  with_items:
    - 'api'
    - 'registry'
  notify:
    - Restart Glance

- name: Configure Glance Rabbit
  ini_file: 
    dest: /etc/glance/glance-api.conf
    section: DEFAULT
    option: notification_driver
    value: messsaging
  notify:
    - Restart Glance

- name: Configure Glance Rabbit
  ini_file: 
    dest: /etc/glance/glance-api.conf
    section: DEFAULT
    option: rabbit_hosts
    value: "{{ common.rabbit_hosts | append(':5672') | join(',')}}"
  notify:
    - Restart Glance

- name: Configure Glance Rabbit
  ini_file: 
    dest: /etc/glance/glance-api.conf
    section: DEFAULT
    option: rabbit_userid
    value: "{{ common.rabbit_user }}"
  notify:
    - Restart Glance

- name: Configure Glance Rabbit
  ini_file: 
    dest: /etc/glance/glance-api.conf
    section: DEFAULT
    option: rabbit_password
    value: "{{ common.rabbit_password }}"
  notify:
    - Restart Glance

- name: Configure Glance Rabbit
  ini_file: 
    dest: /etc/glance/glance-api.conf
    section: DEFAULT
    option: rabbit_virtual_host
    value: /
  notify:
    - Restart Glance

- name: Configure Glance Keystone
  ini_file: 
    dest: "/etc/glance/glance-{{ item }}.conf"
    section: paste_deploy
    option: flavor
    value: keystone
  with_items:
    - 'api'
    - 'registry'
  notify:
    - Restart Glance

- name: Configure Glance Keystone
  ini_file: 
    dest: "/etc/glance/glance-{{ item }}.conf"
    section: keystone_authtoken
    option: auth_host
    value: "{{ common.controller_host }}"
  with_items:
    - 'api'
    - 'registry'
  notify:
    - Restart Glance

- name: Configure Glance Keystone
  ini_file: 
    dest: "/etc/glance/glance-{{ item }}.conf"
    section: keystone_authtoken
    option: auth_port
    value: 35357
  with_items:
    - 'api'
    - 'registry'
  notify:
    - Restart Glance

- name: Configure Glance Keystone
  ini_file: 
    dest: "/etc/glance/glance-{{ item }}.conf"
    section: keystone_authtoken
    option: auth_protocol
    value: http
  with_items:
    - 'api'
    - 'registry'
  notify:
    - Restart Glance

- name: Configure Glance Keystone
  ini_file: 
    dest: "/etc/glance/glance-{{ item }}.conf"
    section: keystone_authtoken
    option: admin_tenant_name
    value: services
  with_items:
    - 'api'
    - 'registry'
  notify:
    - Restart Glance

- name: Configure Glance Keystone
  ini_file: 
    dest: "/etc/glance/glance-{{ item }}.conf"
    section: keystone_authtoken
    option: admin_user
    value: glance
  with_items:
    - 'api'
    - 'registry'
  notify:
    - Restart Glance

- name: Configure Glance Keystone
  ini_file: 
    dest: "/etc/glance/glance-{{ item }}.conf"
    section: keystone_authtoken
    option: admin_password
    value: "{{ glance.password }}" 
  with_items:
    - 'api'
    - 'registry'
  notify:
    - Restart Glance

- name: Configure Glance Store
  ini_file: 
    dest: "/etc/glance/glance-api.conf"
    section: DEFAULT
    option: filesystem_store_datadir
    value: /var/lib/glance/images
  notify:
    - Restart Glance

- name: Configure Glance Store
  ini_file: 
    dest: "/etc/glance/glance-api.conf"
    section: glance_store
    option: stores
    value: glance.store.filesystem.Store
  notify:
    - Restart Glance

- name: Check Glance Database Version
  shell: glance-manage db_version
  register: glance_db_version
  changed_when: false

- name: Populate Glance Database
  run_once: yes
  shell: glance-manage db_sync
  when: glance_db_version.stdout == "0"

- name: Create Glance User
  keystone_user:
    state: present
    endpoint: "http://{{ common.controller_host }}:35357/v2.0"
    token: "{{ keystone.admin_token }}"
    user: glance
    tenant: services
    password: "{{ glance.password }}"

- name: Grant Glance Admin Role
  keystone_user:
    endpoint: "http://{{ common.controller_host }}:35357/v2.0"
    token: "{{ keystone.admin_token }}"
    tenant: services
    user: glance
    role: admin

- name: Create Glance Service And Endpoint
  keystone_service: 
    name: glance
    type: image
    description: "Glance Image Service"
    publicurl: "{{ public_url }}"
    internalurl: "{{ internal_url }}"
    adminurl: "{{ admin_url }}"
    endpoint: "{{ keystone_url }}"
    login_user: admin
    login_password: "{{ keystone.admin_password }}"
    tenant_name: admin
    region: "{{ common.region }}"

- name: Enable Glance Service
  service:
    name: "openstack-glance-{{ item }}"
    enabled: yes
    state: started
  with_items:
    - 'api'
    - 'registry'
