---

- name: Install Heat Packages
  yum: 
    name: '{{ item }}'
    state: latest
  with_items:
    - 'openstack-heat-api'
    - 'openstack-heat-api-cfn'
    - 'openstack-heat-common'
    - 'openstack-heat-engine'
    - 'openstack-heat-api-cloudwatch'
    - 'heat-cfntools'
    - 'python-heatclient'
    - 'openstack-utils'

- name: Configure Heat Debug
  ini_file:
    dest: /etc/heat/heat.conf
    section: DEFAULT
    option: debug
    value: "{{ common.debug }}"
  notify:
   - Restart Heat
   - Restart Heat CloudFormation
   - Restart Heat CloudWatch
   - Restart Heat Engine

- name: Configure Heat SQL Connection
  ini_file: 
    dest: /etc/heat/heat.conf
    section: database
    option: connection
    value: "mysql://{{ heat.dbuser}}:{{heat.dbpassword}}@{{ common.mysql_host}}/{{ heat.dbname }}"
  notify:
   - Restart Heat
   - Restart Heat CloudFormation
   - Restart Heat CloudWatch
   - Restart Heat Engine

- name: Configure Heat Rabbit Backend
  ini_file: 
    dest: /etc/heat/heat.conf
    section: DEFAULT
    option:  rpc_backend
    value: rabbit
  notify:
   - Restart Heat
   - Restart Heat CloudFormation
   - Restart Heat CloudWatch
   - Restart Heat Engine

- name: Configure Heat Rabbit Hosts
  ini_file: 
    dest: /etc/heat/heat.conf
    section: oslo_messaging_rabbit
    option: rabbit_hosts
    value: "{{ common.rabbit_hosts | append(':5672') | join(',')}}"
  notify:
   - Restart Heat
   - Restart Heat CloudFormation
   - Restart Heat CloudWatch
   - Restart Heat Engine

- name: Configure Heat Rabbit User
  ini_file: 
    dest: /etc/heat/heat.conf
    section: oslo_messaging_rabbit
    option: rabbit_userid
    value: "{{ common.rabbit_user }}"
  notify:
   - Restart Heat
   - Restart Heat CloudFormation
   - Restart Heat CloudWatch
   - Restart Heat Engine

- name: Configure Heat Rabbit Password
  ini_file: 
    dest: /etc/heat/heat.conf
    section: oslo_messaging_rabbit
    option: rabbit_password
    value: "{{ common.rabbit_password }}"
  notify:
   - Restart Heat
   - Restart Heat CloudFormation
   - Restart Heat CloudWatch
   - Restart Heat Engine

- name: Configure Heat Rabbit Virtual Host
  ini_file: 
    dest: /etc/heat/heat.conf
    section: oslo_messaging_rabbit
    option: rabbit_virtual_host
    value: /
  notify:
   - Restart Heat
   - Restart Heat CloudFormation
   - Restart Heat CloudWatch
   - Restart Heat Engine

- name: Configure Heat Keystone Strategy
  ini_file: 
    dest: "/etc/heat/heat.conf"
    section: DEFAULT
    option: auth_strategy
    value: keystone
  notify:
   - Restart Heat
   - Restart Heat CloudFormation
   - Restart Heat CloudWatch
   - Restart Heat Engine

- name: Configure Heat Keystone Ec2 Uri
  ini_file: 
    dest: "/etc/heat/heat.conf"
    section: keystone_authtoken
    option: keystone_ec2_uri
    value: "{{ keystone_admin_url }}"
  notify:
   - Restart Heat
   - Restart Heat CloudFormation
   - Restart Heat CloudWatch
   - Restart Heat Engine

- name: Configure Heat Keystone Uri
  ini_file: 
    dest: "/etc/heat/heat.conf"
    section: keystone_authtoken
    option: identity_uri
    value: "{{ keystone_identity_uri }}"
  notify:
   - Restart Heat
   - Restart Heat CloudFormation
   - Restart Heat CloudWatch
   - Restart Heat Engine

- name: Configure Heat Keystone Tenant
  ini_file: 
    dest: "/etc/heat/heat.conf"
    section: keystone_authtoken
    option: admin_tenant_name
    value: services
  notify:
   - Restart Heat
   - Restart Heat CloudFormation
   - Restart Heat CloudWatch
   - Restart Heat Engine

- name: Configure Heat Keystone User
  ini_file: 
    dest: "/etc/heat/heat.conf"
    section: keystone_authtoken
    option: admin_user
    value: heat
  notify:
   - Restart Heat
   - Restart Heat CloudFormation
   - Restart Heat CloudWatch
   - Restart Heat Engine

- name: Configure Heat Keystone Password
  ini_file: 
    dest: "/etc/heat/heat.conf"
    section: keystone_authtoken
    option: admin_password
    value: "{{ heat.password }}" 
  notify:
   - Restart Heat
   - Restart Heat CloudFormation
   - Restart Heat CloudWatch
   - Restart Heat Engine

- name: Configure Heat Metadata Url
  ini_file: 
    dest: "/etc/heat/heat.conf"
    section: DEFAULT
    option: heat_metadata_server_url
    value: "http://'~ heat_host ~':8000"
  notify:
   - Restart Heat
   - Restart Heat CloudFormation
   - Restart Heat CloudWatch
   - Restart Heat Engine

- name: Configure Heat WaitCondition Url
  ini_file: 
    dest: "/etc/heat/heat.conf"
    section: DEFAULT
    option: heat_waitcondition_server_url
    value: "http://'~ heat_host ~':8000/v1/waitcondition"
  notify:
   - Restart Heat
   - Restart Heat CloudFormation
   - Restart Heat CloudWatch
   - Restart Heat Engine

- name: Configure Heat Watch Server Url
  ini_file: 
    dest: "/etc/heat/heat.conf"
    section: DEFAULT
    option: heat_watch_server_url
    value: "http://'~ heat_host ~':8003"
  notify:
   - Restart Heat
   - Restart Heat CloudFormation
   - Restart Heat CloudWatch
   - Restart Heat Engine

- name: Configure Heat Stack user
  ini_file: 
    dest: "/etc/heat/heat.conf"
    section: DEFAULT
    option: heat_stack_user_role
    value: heat_stack_user
  notify:
   - Restart Heat
   - Restart Heat CloudFormation
   - Restart Heat CloudWatch
   - Restart Heat Engine

- name: Populate Heat Database
  run_once: yes
  shell: heat-manage db_sync
  run_once: true
#  when: heat_db_version.stdout == "0"

- name: Create Heat User
  keystone_user:
    state: present
    endpoint: "{{ keystone_admin_url }}"
    token: "{{ keystone.admin_token }}"
    user: heat
    tenant: services
    password: "{{ heat.password }}"

- name: Grant Heat Admin Role
  keystone_user:
    endpoint: "{{ keystone_admin_url }}"
    token: "{{ keystone.admin_token }}"
    tenant: services
    user: heat
    role: admin

- name: Create Heat Service And Endpoint
  keystone_service: 
    name: heat
    type: orchestration
    description: "Heat Identity Service"
    publicurl: "{{ heat_public_url }}"
    internalurl: "{{ heat_internal_url }}"
    adminurl: "{{ heat_admin_url }}"
    endpoint: "{{ keystone_internal_url }}"
    login_user: admin
    login_password: "{{ keystone.admin_password }}"
    tenant_name: admin
    region: "{{ common.region }}"

- name: Create Heat CloudFormation Service And Endpoint
  keystone_service: 
    name: heat-cfn
    type: cloudformation
    description: "Heat CloudFormation Service"
    publicurl: "{{ heat_cfn_public_url }}"
    internalurl: "{{ heat_cfn_internal_url }}"
    adminurl: "{{ heat_cfn_admin_url }}"
    endpoint: "{{ keystone_internal_url }}"
    login_user: admin
    login_password: "{{ keystone.admin_password }}"
    tenant_name: admin
    region: "{{ common.region }}"

- name: Enable Heat Services
  service:
    name: "openstack-heat-{{ item }}"
    enabled: yes
    state: started
  with_items:
   - api
   - api-cfn
   - api-cloudwatch
   - engine
