---

- name: Install Horizon Packages
  yum: 
    name: '{{ item }}'
    state: latest
  with_items:
    - 'httpd'
    - 'mod_wsgi'
    - 'mod_ssl'
    - 'memcached'
    - 'openstack-dashboard'

- name: Configure Horizon
  template:
    src: "horizon/local_settings.{{ version }}"
    dest: "/etc/openstack-dashboard/local_settings"
    backup: yes
  notify:
    - Restart Apache

- name: Enable Apache Service
  service:
   name: httpd
   enabled: yes
   state: started
