---

- name: Set Keystone Variables
  set_fact:
    public_url: "{{ keystone.public_url | default('http://' ~ common.controller_host ~ ':5000/v2.0') }}"
    internal_url: "{{ keystone.internal_url | default('http://' ~ common.controller_host ~ ':5000/v2.0') }}"
    admin_url: "{{ keystone.admin_url | default('http://' ~ common.controller_host ~ ':35357/v2.0') }}"


- name: Install Keystone
  yum: 
    name: '{{ item }}'
    state: latest
  with_items:
    - 'openstack-keystone'
    - 'openstack-utils'
    - 'openstack-selinux'

- name: Configure Keystone Debug
  ini_file: 
    dest: /etc/keystone/keystone.conf
    section: DEFAULT
    option: debug
    value: "{{ common.debug }}"
  notify:
    - Restart Keystone

- name: Configure Keystone SQL Connection 
  ini_file: 
    dest: /etc/keystone/keystone.conf
    section: database
    option: connection
    value: mysql://{{ keystone.dbuser}}:{{keystone.dbpassword}}@{{ common.mysql_host}}/{{ keystone.dbname }}
  notify:
    - Restart Keystone

- name: Configure Keystone Admin Token 
  ini_file: 
    dest: /etc/keystone/keystone.conf
    section: DEFAULT
    option: admin_token
    value: '{{ keystone.admin_token }}'
  notify:
    - Restart Keystone

- name: Configure Keystone token_flush Cron
  cron:
    name: token_flush
    minute: 0
    hour: 0,8,12,16,20
    job: keystone-manage token_flush

- name: Check Keystone Database Version
  shell: keystone-manage db_version
  register: keystone_db_version
  changed_when: false

- name: Populate Keystone Database
  run_once: yes
  shell: keystone-manage db_sync
  when: keystone_db_version.stdout == "0"

- name: Enable Keystone Service
  service:
   name: openstack-keystone
   enabled: yes
   state: started

- name: Create Keystone Client File
  template:
    src: keystonerc_admin.j2
    dest: /root/keystonerc_admin

- name: Create Keystone Admin Tenant
  run_once: yes
  keystone_user:
    endpoint: "http://{{ common.controller_host }}:35357/v2.0"
    token: "{{ keystone.admin_token }}"
    tenant: admin
    tenant_description: "Admin Tenant"

- name: Create Keystone Services Tenant
  run_once: yes
  keystone_user:
    endpoint: "http://{{ common.controller_host }}:35357/v2.0"
    token: "{{ keystone.admin_token }}"
    tenant: services
    tenant_description: "Services Tenant"

- name: Create Keystone Admin User
  run_once: yes
  keystone_user:
    endpoint: "http://{{ common.controller_host }}:35357/v2.0"
    token: "{{ keystone.admin_token }}"
    tenant: admin
    user: admin
    password: "{{ keystone.admin_password }}"

- name: Grant Keystone Admin Role
  run_once: yes
  keystone_user:
    endpoint: "http://{{ common.controller_host }}:35357/v2.0"
    token: "{{ keystone.admin_token }}"
    tenant: admin
    user: admin
    role: admin 

- name: Grant Keystone Member Role
  run_once: yes
  keystone_user:
    endpoint: "http://{{ common.controller_host }}:35357/v2.0"
    token: "{{ keystone.admin_token }}"
    tenant: admin
    user: admin
    role: _member_

- name: Create Keystone Service And Endpoint
  keystone_service:
    name: keystone
    type: identity
    description: "Keystone Identity Service"
    publicurl: "{{ public_url }}"
    internalurl: "{{ internal_url }}"
    adminurl: "{{ admin_url }}"
    endpoint: "{{ admin_url }}"
    token: "{{ keystone.admin_token }}"
    region: "{{ common.region }}"
