---
##- include: debug.yml
##- include: preupgrade.yml
###- include: haproxy.yml
##- include: mysql.yml
##- include: rabbitmq.yml
##- include: mongodb.yml
##- include: keystone.yml tags=keystone
##- include: glance.yml tags=glance
- include: cinder.yml tags=cinder
- include: cinder-volume.yml tags=cinder
##- include: neutron.yml
##- include: nova.yml
##- include: heat.yml
##- include: ceilometer.yml
##- include: dashboard.yml
##- include: postupgrade.yml
