---

- name: Install MongoDB
  yum: 
    name: "{{ item }}"
    state: latest
  with_items:
   - 'mongodb-server'
   - 'python-pymongo'

- name: Configure MongoBD bind_ip
  lineinfile:
    dest: "/etc/mongod.conf"
    line: bind_ip = 0.0.0.0
    regexp: ^bind_ip\s*=
  notify:
    - Restart MongoDB

- name: Enable MongoDB service
  service:
   name: mongod
   enabled: yes
   state: started

- name: Create MongoDB Database And User
  shell: mongo --eval ' db = db.getSiblingDB("ceilometer"); db.addUser(\{user: "{{ ceilometer.dbuser }}", pwd: "{{ ceilometer. dbpassword }}", roles: [ "readWrite", "dbAdmin" ]\})'
  ignore_errors: yes

#- name: Create MongoDB Database User
#  mongodb_user: 
#   database: ceilometer
#   name: "{{ ceilometer.dbuser }}"
#   password: "{{ ceilometer.dbpassword }}"
#   roles: "readWrite,dbAdmin,userAdmin"
#   update_password: always
#   state: present
