---

- name: Set Neutron Variables
  set_fact:
    core_plugin: "{{ neutron.core_plugin | default('ml2') }}"
    service_plugins: "{{ neutron.service_plugins | default(['router']) }}"
    tenant_type: "{{ neutron.tenant_type | default('vxlan') }}"
    network_vlan_ranges: "{{ neutron.network_vlan_ranges | default('physnet1:1000:2999,physnet2:3000:3999') }}"
    type_drivers: "{{ neutron.type_drivers | default(['local,flat,vlan,gre,vxlan']) }}"
    mechanism_drivers: "{{ neutron.mechanism_drivers | default(['openvswitch,l2population']) }}"

- name: Install Neutron Packages
  yum: 
    name: '{{ item }}'
    state: latest
  with_items:
    - 'openstack-neutron'
    - 'openstack-neutron-ml2'
    - 'openstack-neutron-openvswitch'
    - 'openstack-utils'
    - 'openstack-selinux'

- name: Configure Neutron
  template:
    src: "neutron/neutron.conf.{{ version }}"
    dest: "/etc/neutron/neutron.conf"
    backup: yes
  notify:
    - Restart Neutron

- name: Configure Neutron Ml2 Plugin File
  file:
    state: link
    dest: "/etc/neutron/plugin.ini"
    src: "/etc/neutron/plugins/ml2/ml2_conf.ini"
    force: yes
  when: core_plugin == 'ml2'
  notify:
   - Restart Neutron

- name: Configure Neutron
  template:
    src: "neutron/ml2/ml2_conf.ini.{{ version }}"
    dest: "/etc/neutron/plugins/ml2/ml2_conf.ini"
    backup: yes
  when: core_plugin == 'ml2'
  notify:
    - Restart Neutron

- name: Check Neutron Database Version
  shell: neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugin.ini upgrade head
  register: neutron_db_version
  changed_when: false

- name: Populate Neutron Database
  run_once: yes
  shell: neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugin.ini current
  run_once: true
  when: "'OK' not in neutron_db_version"

- name: Create Neutron User
  keystone_user:
    state: present
    endpoint: "{{ keystone_admin_url }}"
    token: "{{ keystone.admin_token }}"
    user: neutron
    tenant: services
    password: "{{ neutron.password }}"

- name: Grant Neutron Admin Role
  keystone_user:
    endpoint: "{{ keystone_admin_url }}"
    token: "{{ keystone.admin_token }}"
    tenant: services
    user: neutron
    role: admin

- name: Create Neutron Service And Endpoint
  keystone_service: 
    name: neutron
    type: network
    description: "Neutron Networking Service"
    publicurl: "{{ neutron_public_url }}"
    internalurl: "{{ neutron_internal_url }}"
    adminurl: "{{ neutron_admin_url }}"
    endpoint: "{{ keystone_internal_url }}"
    login_user: admin
    login_password: "{{ keystone.admin_password }}"
    tenant_name: admin
    region: "{{ common.region }}"

- name: Enable Neutron Service
  service:
    name: "neutron-server"
    enabled: yes
    state: started
