---

- name: Install Neutron Dhcp Packages
  yum: 
    name: '{{ item }}'
    state: latest
  with_items:
    - 'openstack-neutron'
    - 'openstack-neutron-ml2'
    - 'openstack-neutron-openvswitch'
    - 'openstack-utils'
    - 'openstack-selinux'

- name: Configure Neutron Dhcp
  template:
    src: "neutron/dhcp_agent.ini.{{version}}"
    dest: "/etc/neutron/dhcp_agent.ini"
    backup: yes
  notify:
   - Restart Neutron Dhcp

- name: Enable Neutron Dhcp Service
  service:
    name: "neutron-dhcp-agent"
    enabled: yes
    state: started
