---

- name: Install Neutron Dhcp Packages
  yum: 
    name: '{{ item }}'
    state: latest
  with_items:
    - 'openstack-neutron'
    - 'openstack-neutron-ml2'
    - 'openstack-neutron-openvswitch'
    - 'openstack-utils'
    - 'openstack-selinux'

- name: Configure Neutron Dhcp Keystone
  ini_file: 
    dest: "/etc/neutron/dhcp_agent.ini"
    section: DEFAULT
    option: auth_strategy
    value: keystone
  notify:
   - Restart Neutron Dhcp

- name: Configure Neutron Dhcp Keystone Uri
  ini_file: 
    dest: "/etc/neutron/dhcp_agent.ini"
    section: keystone_authtoken
    option: identity_uri
    value: "{{ keystone_identity_uri }}"
  notify:
   - Restart Neutron Dhcp

- name: Configure Neutron Dhcp Keystone Tenant
  ini_file: 
    dest: "/etc/neutron/dhcp_agent.ini"
    section: keystone_authtoken
    option: admin_tenant_name
    value: services
  notify:
   - Restart Neutron Dhcp

- name: Configure Neutron Dhcp Keystone User
  ini_file: 
    dest: "/etc/neutron/dhcp_agent.ini"
    section: keystone_authtoken
    option: admin_user
    value: neutron
  notify:
   - Restart Neutron Dhcp

- name: Configure Neutron Dhcp Keystone Password
  ini_file: 
    dest: "/etc/neutron/dhcp_agent.ini"
    section: keystone_authtoken
    option: admin_password
    value: "{{ neutron.password }}" 
  notify:
   - Restart Neutron Dhcp

- name: Configure Neutron Dhcp Interface Driver
  ini_file: 
    dest: "/etc/neutron/dhcp_agent.ini"
    section: DEFAULT
    option: interface_driver
    value: neutron.agent.linux.interface.OVSInterfaceDriver
  notify:
   - Restart Neutron Dhcp

- name: Enable Neutron Dhcp Service
  service:
    name: "neutron-dhcp-agent"
    enabled: yes
    state: started
