---

- name: Install Swift Packages
  yum: 
    name: '{{ item }}'
    state: latest
  with_items:
    - 'openstack-swift-proxy'
    - 'openstack-swift-plugin-swift3'
    - 'memcached'
    - 'python-swiftclient'

- name: Ensure Swift Ownership
  file:
    path: "/etc/swift"
    state: directory
    recurse: yes
    owner: root
    group: swift

- name: Configure Swift Keystone Ip
  ini_file:
    dest: "/etc/swift/swift.conf"
    section: filter:authtoken
    option: auth_host
    value: "{{ keystone_host }}"
  notify:
   - Restart Swift Proxy

- name: Configure Swift Keystone Ip
  ini_file:
    dest: "/etc/swift/swift.conf"
    section: "filter:authtoken"
    option: auth_host
    value: "{{ keystone_host }}"
  notify:
   - Restart Swift Proxy

- name: Configure Swift Keystone Tenant
  ini_file:
    dest: "/etc/swift/swift.conf"
    section: "filter:authtoken"
    option: admin_tenant_name
    value: services
  notify:
   - Restart Swift Proxy

- name: Configure Swift Keystone User
  ini_file:
    dest: "/etc/swift/swift.conf"
    section: "filter:authtoken"
    option: admin_user
    value: swift
  notify:
   - Restart Swift Proxy

- name: Configure Swift Keystone Password
  ini_file:
    dest: "/etc/swift/swift.conf"
    section: "filter:authtoken"
    option: admin_password
    value: " {{swift.password }} "
  notify:
   - Restart Swift Proxy

- name: Create Swift Ring Objects
  shell: "swift-ring-builder /etc/swift/{{ item }}.builder create {{ swift_partition }} {{ swift_replicas }} 1"
  with_items:
   - 'object'
   - 'account'
   - 'container'

- name: Add Swift Ring Objects Devices
  shell: "swift-ring-builder /etc/swift/object.builder add z1-{{ item.value.ip }}:6201/{{ item.value.devices.0 }} 100"
  with_dict: "{{ swift.storage_nodes }}"

- name: Add Swift Ring Container Devices
  shell: "swift-ring-builder /etc/swift/container.builder add z1-{{ item.value.ip }}:6202/{{ item.value.devices.0 }} 100"
  with_dict: "{{ swift.storage_nodes }}"

- name: Add Swift Ring Account Devices
  shell: "swift-ring-builder /etc/swift/account.builder add z1-{{ item.value.ip }}:6200/{{ item.value.devices.0 }} 100"
  with_dict: "{{ swift.storage_nodes }}"

- name: Rebalance Swift Rings
  shell: "swift-ring-builder /etc/swift/{{ item }}.builder rebalance"
  with_items:
   - 'object'
   - 'account'
   - 'container'

- name: Create Swift User
  keystone_user:
    state: present
    endpoint: "{{ keystone_admin_url }}"
    token: "{{ keystone.admin_token }}"
    user: swift
    tenant: services
    password: "{{ swift.password }}"

- name: Grant Swift Admin Role
  keystone_user:
    endpoint: "{{ keystone_admin_url }}"
    token: "{{ keystone.admin_token }}"
    tenant: services
    user: swift
    role: admin

- name: Create Swift Service And Endpoint
  keystone_service:
    name: swift
    type: object-store
    description: "Swift Object Service"
    publicurl: "{{ swift_public_url }}"
    internalurl: "{{ swift_internal_url }}"
    adminurl: "{{ swift_admin_url }}"
    endpoint: "{{ keystone_internal_url }}"
    login_user: admin
    login_password: "{{ keystone.admin_password }}"
    tenant_name: admin
    region: "{{ common.region }}"

- name: Enable Swift Proxy
  service:
   name: "{{ item }}"
   enabled: yes
   state: started
  with_items:
    - 'memcached'
    - 'openstack-swift-proxy'
