---

- name: Set Hosts
  set_fact:
    keystone_host: "{{ [keystone.host, common.controller_host] | first_found | default('127.0.0.1') }}"
    glance_host: "{{ [glance.host, common.controller_host] | first_found | default('127.0.0.1') }}"
    cinder_host: "{{ [cinder.host, common.controller_host] | first_found | default('127.0.0.1') }}"
    neutron_host: "{{ [neutron.host, common.controller_host] | first_found | default('127.0.0.1') }}"
    nova_host: "{{ [nova.host, common.controller_host] | first_found | default('127.0.0.1') }}"
    heat_host: "{{ [heat.host, common.controller_host] | first_found | default('127.0.0.1') }}"
    ceilometer_host: "{{ [ceilometer.host, common.controller_host] | first_found | default('127.0.0.1') }}"

- name: Set Variables
  set_fact:
    keystone_public_url: "{{ keystone.public_url | default('http://' ~ keystone_host ~ ':5000/v2.0') }}"
    keystone_internal_url: "{{ keystone.internal_url | default('http://' ~ keystone_host ~ ':5000/v2.0') }}"
    keystone_admin_url: "{{ keystone.admin_url | default('http://' ~ keystone_host ~ ':35357/v2.0') }}"
    keystone_identity_uri: "{{ 'http://' ~ keystone_host ~ ':35357/' }}"
    glance_public_url: "{{ glance.public_url | default('http://' ~ glance_host ~ ':9292') }}"
    glance_internal_url: "{{ glance.internal_url | default('http://' ~ glance_host ~ ':9292') }}"
    glance_admin_url: "{{ glance.admin_url | default('http://' ~ glance_host ~ ':9292') }}"
    glance_api_servers: "{{ [glance.hosts, common.glance_hosts] | first_found | default(['127.0.0.1']) }}"
    cinder_public_url: "{{ cinder.public_url | default('http://' ~ cinder_host ~ ':8776/v1/%(tenant_id)s') }}"
    cinder_internal_url: "{{ cinder.internal_url_v2 | default('http://' ~ cinder_host ~ ':8776/v1/%(tenant_id)s') }}"
    cinder_admin_url: "{{ cinder.admin_url | default('http://' ~ cinder_host ~ ':8776/v1/%(tenant_id)s') }}"
    cinderv2_public_url: "{{ cinder.public_url_v2 | default('http://' ~ cinder_host ~ ':8776/v2/%(tenant_id)s') }}"
    cinderv2_internal_url: "{{ cinder.internal_url_v2 | default('http://' ~ cinder_host ~ ':8776/v2/%(tenant_id)s') }}"
    cinderv2_admin_url: "{{ cinder.admin_url_v2 | default('http://' ~ cinder_host ~ ':8776/v2/%(tenant_id)s') }}"
    neutron_public_url: "{{ neutron.public_url | default('http://' ~ neutron_host ~ ':9696') }}"
    neutron_internal_url: "{{ neutron.internal_url | default('http://' ~ neutron_host ~ ':9696') }}"
    neutron_admin_url: "{{ neutron.admin_url | default('http://' ~ neutron_host ~ ':9696') }}"
    nova_public_url: "{{ nova.public_url | default('http://' ~ nova_host ~ ':8774/v2/%(tenant_id)s') }}"
    nova_internal_url: "{{ nova.internal_url | default('http://' ~ nova_host ~ ':8774/v2/%(tenant_id)s') }}"
    nova_admin_url: "{{ nova.admin_url | default('http://' ~ nova_host ~ ':8774/v2/%(tenant_id)s') }}"
    heat_public_url: "{{ heat.public_url | default('http://' ~ heat_host ~ ':8004/v1/%(tenant_id)s') }}"
    heat_internal_url: "{{ heat.internal_url | default('http://' ~ heat_host ~ ':8004/v1/%(tenant_id)s') }}"
    heat_admin_url: "{{ heat.admin_url | default('http://' ~ heat_host ~ ':8004/v1/%(tenant_id)s') }}"
    heat_cfn_public_url: "{{ heat.public_url | default('http://' ~ heat_host ~ ':8000/v1') }}"
    heat_cfn_internal_url: "{{ heat.internal_url | default('http://' ~ heat_host ~ ':8000/v1') }}"
    heat_cfn_admin_url: "{{ heat.admin_url | default('http://' ~ heat_host ~ ':8000/v1') }}"
    ceilometer_public_url: "{{ ceilometer.public_url | default('http://' ~ ceilometer_host ~ ':8777') }}"
    ceilometer_internal_url: "{{ ceilometer.internal_url | default('http://' ~ ceilometer_host ~ ':8777') }}"
    ceilometer_admin_url: "{{ ceilometer.admin_url | default('http://' ~ ceilometer_host ~ ':8777') }}"
