---
- name: Set Mitaka  Repos
  hosts: newyork
  remote_user: cloud-user
  gather_facts: true
  become: yes
  become_user: root
  become_method: sudo
  tasks:

  - name: Activate Mitaka Repos
    redhat_repos:
     state: present
     only: yes
     repos:
      - rhel-7-server-rpms
      - rhel-7-server-rh-common-rpms
      - rhel-7-server-openstack-9-rpms
      - rhel-ha-for-rhel-7-server-rpms
      - rhel-7-server-extras-rpms
