---

- name: Set Ceilometer Handlers
  set_fact:
    ceilometer_handlers: ['Restart Ceilometer','Restart Ceilometer Central','Restart Ceilometer Collector','Restart Ceilometer Alarm Evaluator','Restart Ceilometer Alarm Notifier','Restart Ceilometer Notification']
  when: version in ['kilo', 'liberty']

- name: Set Ceilometer Handlers
  set_fact:
    ceilometer_handlers: ['Restart Ceilometer','Restart Ceilometer Central','Restart Ceilometer Collector','Restart Ceilometer Notification']
  when: version not in ['kilo', 'liberty']

- name: Install Ceilometer Packages
  package: 
    name: '{{ item }}'
    state: latest
  with_items: "{{ ceilometer_packages }}"

- name: Configure Ceilometer
  template:
    src: "ceilometer.conf.{{ version }}"
    dest: "/etc/ceilometer/ceilometer.conf"
    backup: yes
  notify: "{{ ceilometer_handlers }}"

- name: Create Ceilometer User
  keystone_user:
    state: present
    endpoint: "{{ keystone_admin_url }}"
    token: "{{ keystone.admin_token }}"
    user: ceilometer
    tenant: services
    password: "{{ ceilometer.password }}"

- name: Create Ceilometer ResellerAdmin Role
  run_once: yes
  keystone_user:
    endpoint: "{{ keystone_admin_url }}"
    token: "{{ keystone.admin_token }}"
#   tenant: admin
    role: ResellerAdmin


- name: Grant Ceilometer Admin Role
  keystone_user:
    endpoint: "{{ keystone_admin_url }}"
    token: "{{ keystone.admin_token }}"
    tenant: services
    user: ceilometer
    role: admin

- name: Grant Ceilometer ResellerAdmin Role
  keystone_user:
    endpoint: "{{ keystone_admin_url }}"
    token: "{{ keystone.admin_token }}"
    tenant: services
    user: ceilometer
    role: ResellerAdmin

- name: Create Ceilometer Service And Endpoint
  keystone_service: 
    name: ceilometer
    type: metering
    description: "Ceilometer Telemetry Service"
    publicurl: "{{ ceilometer_public_url }}"
    internalurl: "{{ ceilometer_internal_url }}"
    adminurl: "{{ ceilometer_admin_url }}"
    endpoint: "{{ keystone_internal_url }}"
    login_user: admin
    login_password: "{{ keystone.admin_password }}"
    tenant_name: admin
    region: "{{ common.region }}"

- name: Enable Ceilometer Services
  service:
    name: "{{ ceilometer_service }}-{{ item }}"
    enabled: yes
    state: started
  with_items:
   - api
   - collector
   - central
   - notification
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Enable Ceilometer Services
  service:
    name: "{{ ceilometer_service }}-{{ item }}"
    enabled: yes
    state: started
  with_items:
   - api
   - collector
   - agent-central
   - agent-notification
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'


- name: Enable Ceilometer Alarm Services
  service:
    name: "{{ ceilometer_service }}-{{ item }}"
    enabled: yes
    state: started
  with_items:
   - alarm-evaluator
   - alarm-notifier
   - notification
  when: version in ['kilo','liberty'] and ( ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' )

- name: Enable Ceilometer Alarm Services
  service:
    name: "{{ ceilometer_service }}-{{ item }}"
    enabled: yes
    state: started
  with_items:
   - alarm-evaluator
   - alarm-notifier
   - agent-notification
  when: version in ['kilo','liberty'] and ( ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' )
