---

- name: Install Rabbitmq Packages
  package: 
    name: "{{ item }}"
    state: latest
  with_items: "{{ rabbitmq_packages }}"

- name: Enable Rabbitmq service
  service:
   name: "{{ rabbitmq_service }}"
   enabled: yes
   state: started
