---

- name: Install Neutron Dhcp Packages
  package: 
    name: '{{ item }}'
    state: latest
  with_items: "{{ neutron_packages }}"

- name: Configure Neutron Dhcp
  template:
    src: "dhcp_agent.ini.{{version}}"
    dest: "/etc/neutron/dhcp_agent.ini"
    backup: yes
  notify:
   - Restart Neutron Dhcp

- name: Enable Neutron Dhcp Service
  service:
    name: "neutron-dhcp-agent"
    enabled: yes
    state: started
