---

- name: Install MariaDB Packages
  package: 
    name: '{{ item }}'
    state: latest
  with_items: "{{ mysql_packages }}"

- name: Enable MariaDB Service
  service:
   name: "{{ mysql_service }}"
   enabled: yes
   state: started

- name: Create Dbs
  mysql_db:
   name: "{{ item }}" 
   state: "present"
   encoding: utf8
  with_items: "{{ mysql.databases }}"

- name: Create Db Users
  mysql_user:
   name: "{{ vars[item[0]]['dbuser'] }}"
   password: "{{ vars[item[0]]['dbpassword'] }}"
#   priv: "*.*:ALL,GRANT"
   priv: "{{ item[0] }}.*:ALL,GRANT"
   append_privs: yes
   state: "present"
   host: "{{ item[1] }}"
  with_nested:
   - "{{ mysql.databases}}"
   - ['localhost', '%' ]
