---

- name: Install MariaDB Packages
  package: 
    name: '{{ item }}'
    state: latest
  with_items: "{{ mysql_packages }}"

- name: Enable MariadDB Service
  service:
   name: "{{ mysql_service }}"
   enabled: yes
   state: started

- name: Create Dbs
  mysql_db:
   name: "{{ item }}" 
   state: "present"
   encoding: utf8
  with_items: "{{ mysql.databases }}"

- name: Create Db Users
  mysql_user:
   name: "{{ vars[item[0]]['dbuser'] }}"
   password: "{{ vars[item[0]]['dbpassword'] }}"
   priv: "*.*:ALL,GRANT"
   state: "present"
   host: "{{ item[1] }}"
  with_nested:
   - "{{ mysql.databases}}"
   - ['localhost', '%' ]

- name: Create Nova Api Db 
  mysql_db:
   name: "{{ nova.api_dbname }}" 
   state: "present"
   encoding: utf8
  when: version not in ['kilo','liberty']

- name: Create User for Nova Api Db
  mysql_user:
   name: "{{ nova.dbuser }}"
   password: "{{ nova.dbpassword }}"
   priv: "*.*:ALL,GRANT"
   state: "present"
   host: "{{ item }}"
  with_items:
   - 'localhost'
   - '%'
  when: version not in ['kilo','liberty']

