- include: variables.yml
  tags:
   - allinone
   - api
   - ceilometer
   - cinder
   - common
   - compute
   - debug
   - glance
   - haproxy
   - heat
   - horizon
   - keystone
   - mongodb
   - mysql
   - neutron
   - nova
   - pacemaker
   - rabbitmq
   - swift

- name: Create Common Keystone Client File
  template:
    src: keystonerc_admin.j2
    dest: /root/keystonerc_admin
  tags:
   - allinone
   - api
   - ceilometer
   - cinder
   - common
   - compute
   - debug
   - glance
   - heat
   - horizon
   - keystone
   - neutron
   - nova
   - swift

- name: Create Common Keystone V3 Client File
  template:
    src: keystonerc_admin_v3.j2
    dest: /root/keystonerc_admin_v3
  tags:
   - allinone
   - api
   - ceilometer
   - cinder
   - common
   - compute
   - debug
   - glance
   - heat
   - horizon
   - keystone
   - neutron
   - nova
   - swift
