apache_service: httpd
apache_dir: /etc/httpd/conf.d
wsgi_file: wsgi-keystone.conf.redhat
haproxy_packages:
 - 'haproxy'
mysql_packages:
 - 'mariadb-galera-server'
 - 'MySQL-python'
mysql_service: mariadb
mongodb_packages:
 - 'mongodb-server'
 - 'python-pymongo'
 - 'mongodb'
mongodb_conf_file: /etc/mongod.conf
mongodb_service: mongod
rabbitmq_packages:
 - 'rabbitmq-server'
rabbitmq_service: rabbitmq-server
openstack_packages:
 - 'openstack-utils'
 - 'openstack-selinux'
 - 'python-openstackclient'
 - 'python-memcached'
 - 'python-oslo-log'
 - 'python-keystoneclient'
 - 'python-cinderclient'
 - 'python-heatclient'
 - 'python-ceilometer'
 - 'python-ceilometerclient'
 - 'python-swiftclient'
keystone_packages:
 - 'openstack-keystone'
 - 'python-keystonemiddleware'
 - 'httpd'
 - 'mod_wsgi'
 - 'memcached'
 - 'python-memcached'
keystone_service: openstack-keystone
glance_packages:
 - 'openstack-glance'
glance_services:
 - 'openstack-glance-api'
 - 'openstack-glance-registry'
cinder_packages:
 - 'openstack-cinder'
 - 'openstack-utils'
 - 'device-mapper-multipath'
cinder_services: 
 - 'openstack-cinder-api'
 - 'openstack-cinder-scheduler'
cinder_volume_service: 'openstack-cinder-volume'
neutron_packages:
 - 'openvswitch'
 - 'openstack-neutron'
 - 'openstack-neutron-ml2'
 - 'openstack-neutron-openvswitch'
neutron_service: neutron-server
neutron_ovs_service: neutron-openvswitch-agent
neutron_dhcp_service: neutron-dhcp-agent
neutron_l3_services:
 - neutron-l3-agent
 - neutron-metadata-agent
openvswitch_service: openvswitch
nova_packages:
 - 'openstack-nova-api'
 - 'openstack-nova-conductor'
 - 'openstack-nova-scheduler'
 - 'openstack-nova-novncproxy'
 - 'openstack-nova-console'
nova_services:
 - 'openstack-nova-api'
 - 'openstack-nova-conductor'
 - 'openstack-nova-scheduler'
 - 'openstack-nova-novncproxy'
 - 'openstack-nova-consoleauth'
 - 'openstack-nova-console'
nova_compute_packages:
 - 'libvirt-daemon'
 - 'openstack-nova-compute'
 - 'openstack-selinux'
nova_compute_service: openstack-nova-compute
nova_compute_ceilometer_packages:
 - 'openstack-ceilometer-compute'
heat_packages:
 - 'openstack-heat-api'
 - 'openstack-heat-api-cfn'
 - 'openstack-heat-common'
 - 'openstack-heat-engine'
 - 'openstack-heat-api-cloudwatch'
 - 'heat-cfntools'
heat_services:
 - 'openstack-heat-api'
 - 'openstack-heat-api-cfn'
 - 'openstack-heat-api-cloudwatch'
 - 'openstack-heat-engine'
ceilometer_packages:
 - 'openstack-ceilometer-api'
 - 'openstack-ceilometer-central'
 - 'openstack-ceilometer-collector'
 - 'openstack-ceilometer-common'
 - 'openstack-ceilometer-compute'
 - 'openstack-ceilometer-alarm'
 - 'openstack-ceilometer-notification'
ceilometer_services:
 - 'openstack-ceilometer-api'
 - 'openstack-ceilometer-collector'
 - 'openstack-ceilometer-central'
 - 'openstack-ceilometer-notification'
ceilometer_alarm_services:
 - 'openstack-ceilometer-alarm-evaluator'
 - 'openstack-ceilometer-alarm-notifier'
 - 'openstack-ceilometer-notification'
ceilometer_compute_service: openstack-ceilometer-compute
ceilometer_notification_service: openstack-ceilometer-notification
swift_packages:
 - 'openstack-swift-proxy'
 - 'openstack-swift-plugin-swift3'
 - 'memcached'
swift_storage_packages:
 - 'rsync'
 - 'xinetd'
 - 'openstack-swift-object'
 - 'openstack-swift-container'
 - 'openstack-swift-account'
swift_services:
 - 'openstack-swift-proxy'
 - 'memcached'
swift_storage_services:
 - 'xinetd'
 - 'openstack-swift-object'
 - 'openstack-swift-container'
 - 'openstack-swift-account'
horizon_packages:
 - 'httpd'
 - 'mod_wsgi'
 - 'mod_ssl'
 - 'memcached'
 - 'openstack-dashboard'
aodh_packages:
 - 'openstack-aodh-api'
 - 'openstack-aodh-evaluator'
 - 'openstack-aodh-notifier'
 - 'openstack-aodh-listener'
 - 'openstack-aodh-expirer'
 - 'python-aodhclient'
aodh_services:
 - 'openstack-aodh-api'
 - 'openstack-aodh-evaluator'
 - 'openstack-aodh-notifier'
 - 'openstack-aodh-listener'
redis_packages:
 - 'redis'
redis_service: redis
designate_packages:
 - 'openstack-designate-api'
 - 'openstack-designate-central'
 - 'openstack-designate-sink'
 - 'openstack-designate-pool-manager'
 - 'openstack-designate-mdns'
 - 'openstack-designate-common'
 - 'python-designate'
 - 'python-designateclient'
 - 'openstack-designate-agent'
designate_services:
 - 'openstack-designate-api'
 - 'openstack-designate-central'
 - 'openstack-designate-mdsn'
 - 'openstack-designate-pool-manager'
bind_packages:
 - 'bind'
 - 'bind-utils'
bind_service: named
bind_conf_dir: /etc
bind_user: named
bind_group: named
magnum_packages:
 - 'openstack-magnum-api'
 - 'openstack-magnum-conductor'
 - 'python2-magnumclient.noarch'
magnum_services:
 - 'openstack-magnum-api'
 - 'openstack--magnum-conductor'
