apache_service: httpd
apache_dir: /etc/httpd/conf.d
wsgi_file: wsgi-keystone.conf.redhat
haproxy_packages:
 - 'haproxy'
mysql_packages:
 - 'mariadb-galera-server'
 - 'MySQL-python'
mysql_service: mariadb
mongodb_packages:
 - 'mongodb-server'
 - 'python-pymongo'
 - 'mongodb'
mongodb_conf_file: /etc/mongod.conf
mongodb_service: mongod
rabbitmq_packages:
 - 'rabbitmq-server'
keystone_packages:
 - 'openstack-keystone'
 - 'openstack-utils'
 - 'openstack-selinux'
 - 'python-openstackclient'
 - 'python-keystonemiddleware'
 - 'httpd'
 - 'mod_wsgi'
 - 'memcached'
 - 'python-memcached'
keystone_service: openstack-keystone
glance_packages:
 - 'openstack-glance'
 - 'openstack-utils'
 - 'openstack-selinux'
 - 'python-openstackclient'
glance_service: openstack-glance
cinder_packages:
 - 'openstack-cinder'
 - 'openstack-utils'
 - 'openstack-selinux'
 - 'device-mapper-multipath'
 - 'python-openstackclient'
 - 'python-oslo-log'
cinder_service: openstack-cinder
neutron_packages:
 - 'openvswitch'
 - 'openstack-neutron'
 - 'openstack-neutron-ml2'
 - 'openstack-neutron-openvswitch'
 - 'openstack-utils'
 - 'openstack-selinux'
 - 'python-openstackclient'
neutron_service: neutron-server
neutron_ovs_service: neutron-openvswitch-agent
neutron_dhcp_service: neutron-dhcp-agent
neutron_l3_services:
 - neutron-l3-agent
 - neutron-metadata-agent
openvswitch_service: openvswitch
nova_packages:
 - 'openstack-nova-api'
 - 'openstack-nova-conductor'
 - 'openstack-nova-scheduler'
 - 'openstack-nova-novncproxy'
 - 'openstack-nova-console'
 - 'openstack-utils'
 - 'python-cinderclient'
 - 'openstack-selinux'
 - 'python-openstackclient'
nova_service: openstack-nova
nova_compute_packages:
 - 'libvirt-daemon'
 - 'openstack-nova-compute'
 - 'openstack-utils'
 - 'python-cinderclient'
 - 'openstack-selinux'
nova_compute_service: openstack-nova-compute
nova_compute_ceilometer_packages:
 - 'openstack-ceilometer-compute'
 - 'python-ceilometer'
 - 'python-ceilometerclient'
heat_packages:
 - 'openstack-heat-api'
 - 'openstack-heat-api-cfn'
 - 'openstack-heat-common'
 - 'openstack-heat-engine'
 - 'openstack-heat-api-cloudwatch'
 - 'heat-cfntools'
 - 'python-heatclient'
 - 'openstack-utils'
 - 'python-openstackclient'
heat_service: openstack-heat
ceilometer_packages:
 - 'openstack-ceilometer-api'
 - 'openstack-ceilometer-central'
 - 'openstack-ceilometer-collector'
 - 'openstack-ceilometer-common'
 - 'openstack-ceilometer-compute'
 - 'openstack-ceilometer-alarm'
 - 'openstack-ceilometer-notification'
 - 'openstack-utils'
 - 'python-ceilometer'
 - 'python-ceilometerclient'
 - 'openstack-selinux'
 - 'python-openstackclient'
ceilometer_service: openstack-ceilometer
ceilometer_compute_service: openstack-ceilometer-compute
ceilometer_notification_service: openstack-ceilometer-notification
swift_packages:
 - 'openstack-swift-proxy'
 - 'openstack-swift-plugin-swift3'
 - 'memcached'
 - 'python-swiftclient'
swift_storage_packages:
 - 'rsync'
 - 'xinetd'
 - 'openstack-swift-object'
 - 'openstack-swift-container'
 - 'openstack-swift-account'
 - 'python-swiftclient'
swift_service: openstack-swift
horizon_packages:
 - 'httpd'
 - 'mod_wsgi'
 - 'mod_ssl'
 - 'memcached'
 - 'openstack-dashboard'
aodh_packages:
 - 'openstack-aodh-api'
 - 'openstack-aodh-evaluator'
 - 'openstack-aodh-notifier'
 - 'openstack-aodh-listener'
 - 'openstack-aodh-expirer'
 - 'python-aodhclient'
 - 'python-openstackclient'
aodh_service: openstack-aodh
