---

- name: Install Bind Packages
  package: 
    name: '{{ item }}'
    state: latest
  with_items: "{{ bind_packages }}"

- name: Create Bind Rndc Key
  shell: rndc-confgen -a creates={{ bind_conf_dir }}/rndc.key

- name: Set Permission to Bind Rndc Key
  file:
   path: "{{ bind_conf_dir }}/rndc.key"
   owner: "{{ bind_user }}"
   group: "{{ bind_group }}"
   mode: 0600
  
- name: Register Bind Rndc Key
  shell: cat {{ bind_conf_dir }}/rndc.key
  register: rndc_key

- name: Create Bind Rndc Conf File
  template:
   src: "{{ role_path }}/templates/rndc.conf"
   dest: /etc/rndc.conf

- name: Configure Bind
  template:
   src: "{{ item }}"
   dest: "{{ bind_conf_dir }}/named.conf"
   backup: yes
  with_first_found:
   - '{{ role_path }}/templates/named.conf.{{ ansible_os_family }}'
   - '{{ role_path }}/templates/named.conf.default'
  notify:
   - Restart Bind

- name: Enable Bind Service
  service:
   name: "{{ bind_service }}"
   enabled: yes
   state: started
