---

- name: Install Bind Packages
  package: 
    name: '{{ item }}'
    state: latest
  with_items: "{{ bind_packages }}"

- name: Create Bind Rndc Key
  shell: rndc-confgen -a creates=/etc/rndc.key

- name: Set Permission to Bind Rndc Key
  file:
   path: /etc/rndc.key
   owner: named
   group: named
   mode: 0600
  
- name: Register Bind Rndc Key
  shell: cat /etc/rndc.key
  register: rndc_key

- name: Create Bind Rndc Conf File
  template:
   src: "{{ role_path }}/templates/rndc.conf"
   dest: /etc/rndc.conf

- name: Configure Bind
  copy:
   src: "{{ role_path }}/files/named.conf"
   dest: /etc/named.conf

- name: Enable Bind Service
  service:
   name: "{{ bind_service }}"
   enabled: yes
   state: started
