---

- name: Install Bind Packages
  package: 
    name: '{{ item }}'
    state: latest
  with_items: "{{ bind_packages }}"

- name: Create Bind Rndc Key
  shell: rndc-confgen -a creates=/etc/rndc.key

- name: Register Bind Rndc Key
  shell: grep secret /etc/rndc.key  | awk -F' ' '{print $2}'
  register: rndc_key

- name: Include Bind Rndc Key File
  lineinfile:
   state: present
   dest: /etc/named.conf
   line: 'include "/etc/rndc.key";'

- name: Enable Bind to listen on all interfaces
  lineinfile:
   dest: /etc/named.conf
   regexp: "listen-on port 53"
   line: "        listen-on port 53 { any; };"

- name: Enable Bind Recusion
  lineinfile:
   dest: /etc/named.conf
   regexp: "allow-query"
   line: "        allow-query { any; };\n        allow-new-zones yes;"

- name: Include Bind Controls File
  lineinfile:
   state: present
   dest: /etc/named.conf
   line: 'include "/etc/named.conf.controls";'

- name: Create Bind Controls File
  copy:
   src: "{{ role_path }}/files/named.conf.controls"
   dest: /etc/named.conf.controls

- name: Enable Bind Service
  service:
   name: "{{ bind_service }}"
   enabled: yes
   state: started
